[custom.all.dtc-utils]
type = "local"
path = "."
ipkg = "dtc-utils.ipkg"
test = "test/test.ipkg"

[custom.all.dtc-utils-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.nightly-250916.mk]
type = "github"
url = "https://github.com/buzden/idris2-mk"
commit = "0df0651b12ecc574d5083a361333f80aaaa912ad"
ipkg = "mk.ipkg"
